### ISSUE TITLE
use only female performers

### ISSUE THREAD

**Issue by ferengi82** [Belleyy/Stash-Renamer-Python#2]
hi, realy nice tool.
can you add a switch to use only female performers for renaming?
I like to have the males in Stash, but not in the Filename / Title

**Comment by ferengi82** [comment]
easier as i thought: (not optimal, but it works for me)
 
1. ADD `GENDER = "female" #only performers with this gender will be used` in a new line after DRY_RUN at the beginning of the file
2. modify line 54: `cursor.execute("SELECT name from performers WHERE id=? AND gender=?;", [perf_id,GENDER.upper()])`

**Comment by Belleyy** [comment]
> 
> 
> easier as i thought: (not optimal, but it works for me)
> 
>     1. ADD `GENDER = "female" #only performers with this gender will be used` in a new line after DRY_RUN at the beginning of the file
> 
>     2. modify line 54: `cursor.execute("SELECT name from performers WHERE id=? AND gender=?;", [perf_id,GENDER.upper()])`

Yea should work, i did something different in my PR. I don't tested it but it should work.
If you use my method, thanks to say if it worked for you 😄

**Comment by ferengi82** [comment]
that was fast!
seems to worke fine, thanks!
